services:
  - docker

stages:
- build
- failure

before_script:
  - ln -s $(pwd) /cwd
  - ln -s $(dirname $(pwd)) /hoard

.build: &build
  stage: build
  artifacts:
    when: always
    paths:
    - $(pwd)/.cache/jhbuild/build/gjs/test-suite.log

  script:
    # Clean the hoard (if requested)
    - $(pwd)/test/test-ci.sh INSTALL_GIT
    - commit_message=$(git log -1)
    - 'if [[ $commit_message == *"[clean hoard]"* && -d "/hoard/SAVED" ]]; then
         rm -rf /hoard/SAVED;
       fi'

    # Build dependencies and 'make check' gjs
    - 'if [[ -d "/hoard/SAVED/$OS/jhbuild" ]]; then
         $(pwd)/test/test-ci.sh GET_FILES;
       else
         $(pwd)/test/test-ci.sh BUILD_MOZ;
       fi'
    - $(pwd)/test/test-ci.sh GJS

    # Run extra tests
    - 'if [[ $BUILD_OPTS == *"--enable-installed-tests"* ]]; then
         $(pwd)/test/test-ci.sh GJS_EXTRA;
       fi'

ubuntu_gcc:
  <<: *build
  image: ubuntu:rolling
  variables:
    BASE: ubuntu
    OS: ubuntu:rolling
    CC: gcc
    BUILD_OPTS: "--enable-installed-tests"
  only:
    - master@GNOME/gjs

fedora_gcc:
  <<: *build
  image: fedora:latest
  variables:
    BASE: fedora
    OS: fedora:latest
    CC: gcc
    CPPCHECK: "yes"
    BUILD_OPTS: "--enable-ubsan"

# Failure routine
on_failure:
  stage: failure
  script:
  - echo '-- FAILURE --'
  - 'if [[ -f $(pwd)/.cache/jhbuild/build/gjs/test-suite.log ]]; then
        cat $(pwd)/.cache/jhbuild/build/gjs/test-suite.log;
    else
        echo "-- NO LOG FILE FOUND --";
    fi'
  when: on_failure
